### ISSUE TITLE
Data Center compatibility?

### ISSUE THREAD

**Issue by svante66** [reconquest/atlassian-pull-request-labels#1]
Hey team,
Are you planning making your plugin Data Center compatible?
Cheers,
// Svante

**Comment by seletskiy** [comment]
Hello,

While DC is not directly available from marketplace, it still can be installed via manual upload via Upload app button in Admin Panel. 

However, there is a problem with Oracle DB which we will resolve little bit later.

Which database do you use in your Bitbucket DC setup?

**Comment by svante66** [comment]
Hey,
Thnx for your swift reply. I understand that we can install this manually but due to our large instance we have restricted to plugins fulfilling at least these two criteria:

- proven DC compatibility

- Plugin supported by the vendor

We are running a very large instance and need to evaluate any extension added.
We run Bitbucket with a Postgres 11 AWS RDS in the backend

Cheers,
// Svante

**Comment by seletskiy** [comment]
We can validate that add-on works correctly on our test setup with DC instances using Postgres as a backend, but typical approval process (e.g. DC compatible message at Marketplace) usually takes ~3 month from Atlassian to complete.

If you're still interested and can provide some info about your setup (number of nodes & number of pull requests), we can run very specific test suite.

**Comment by svante66** [comment]
Ok, got it! I am aware that the DC approval process is kind of lengthy. But better safe than sorry. If you can run tests applicable to our current scale that would be great. We have had issues in the past with DC compatible plugins that mess up due to the traffic we see in our instance. We have around 700 PR opened on an average workday and currently there are 1600 open PR.
Checkout attached screenshots

Cheers,
// Svante

**Comment by seletskiy** [comment]
@svante66: Thanks for the info! It's definitely helpful.

And another note: since we've made add-on free (because of particular lack of the interest) it's currently not a priority for us. May you consider purchasing it, so we can escalate testing, DC approval and provide a priority support?

In any way, let's continue discussion via e-mail: we@reconquest.io
