### ISSUE TITLE
Labels field disappears when switching tabs

### ISSUE THREAD

**Issue by rPraml** [reconquest/atlassian-pull-request-labels#2]
Hello,
I noticed the following bug:

- open a Pull request (Labels field will appear on the right side over "learn more"
![grafik](https://user-images.githubusercontent.com/5530228/77470047-58688b80-6e10-11ea-87ea-599a6a792f0f.png)
- switch to an other tab and back to overview
![grafik](https://user-images.githubusercontent.com/5530228/77470026-4dadf680-6e10-11ea-913f-216ea8eb3c0d.png)
- label will disappear (or does not appear again)
![grafik](https://user-images.githubusercontent.com/5530228/77470126-77671d80-6e10-11ea-9cf7-b9ffb8671f70.png)

Current workaround: Reload page

**Comment by kovetskiy** [comment]
Hi @rPraml thanks for the issue, could you share what version of add-on and bitbucket you are running?

**Comment by rPraml** [comment]
Hello @kovetskiy I've the latest version 6.0.1
/edit: Bitbucket version is  v6.10.0

**Comment by kovetskiy** [comment]
@rPraml Please check the latest version of the add-on: v7.0.0

You can download it from the official marketplace page: https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history#b1000150

or can click Upgrade in your Bitbucket instance

Please confirm that the fix works for you too.

**Comment by viceice** [comment]
I'm using v7.1.0 and it works

**Comment by kovetskiy** [comment]
@viceice thanks for the confirmation, it works for us too!
