### ISSUE TITLE
Plugin displays one photo for all reviewers after PRs was filtered by link

### ISSUE THREAD

**Issue by kszorin** [reconquest/atlassian-pull-request-labels#6]
## Steps
We have some link and pull requests (PR) with this link. All PRs have 3 different reviewers.
1. Open all PRs.
2.  Filter PRs by this link.

## Expect
Filtered PRs have unique foto for each reviewers.

## Acually
Each filtered PR have one foto for all reviewer.

![revieweкs](https://user-images.githubusercontent.com/23697687/80165701-2d877800-8606-11ea-8689-0042563dc516.PNG)

**Comment by kovetskiy** [comment]
That definitely sounds as a bug. I'll try to reproduce it. Will keep the issue updated.

**Comment by kovetskiy** [comment]
@kszorin the issue should be fixed now, please check 7.1.0

Changelog: https://labels.reconquest.io/docs/changelog/#710-2020-04-24
Download: https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history#b1000160

**Comment by kovetskiy** [comment]
@kszorin Hi! Could you confirm that the issue is solved for you?

**Comment by kszorin** [comment]
@kovetskiy , hi! Unfortunately other developers can't work with your plugin. Because labels area takes too many place. It's bad for monitors with FullHD resolution.

But I will close bug.

![image-2020-04-23-12-26-17-428](https://user-images.githubusercontent.com/23697687/80370341-2092af00-88ba-11ea-9afe-2c7469abf2e8.png)

**Comment by kovetskiy** [comment]
The add-on is free and open source, you can change whatever css settings you prefer, feel free to send PR.
