### ISSUE TITLE
Get and filter marked via label PR via API

### ISSUE THREAD

**Issue by BattleLoot** [reconquest/atlassian-pull-request-labels#9]
Hi!

It's possible to filter or try to find out PR via API in repository, where this plugin have installed. I would like to filter PR via some predefined label, which already created on repo side and assigned to PR

For example, I got all PR via https://{{ HOST }}:{{ PORT }}/rest/api/1.0/projects/{{ PROJECT }}/repos/{{ REPO_NAME }}/pull-requests?limit=1000&state=OPEN and if needed, just add other filter by default functionality of bitbucket. However, did't see any labels in response.

Thanks!

**Comment by seletskiy** [comment]
To filter PRs by labels you need to use API which is provided by this add-on, not just standard BB API.

The easiest way to find this URL is to open your browser's Network Inspector, open the BB page where several PRs could be seen, click on the Label Filter, and select some Label to filter by.

After that, you should see the endpoint which labels add-on is calling in the Inspector.

**Comment by BattleLoot** [comment]
Awesome, it works. Much appreciated, thank you very much!
